example:
  property: I AM THE DEFAULT

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  cloud:
    stream:
      bindings:
        movieSessionOutput-out-0:
          destination: orgChangeTopic
          content-type: application/json
      kafka:
        binder:
          brokers: localhost:9092
          auto-create-topics: true